### ISSUE TITLE
Cannot install from ankiweb or by building myself

### ISSUE THREAD

**Issue by MinmoTech** [abdnh/aw-watcher-anki#1]
When trying to install from ankiweb with the code `567877061` I get this error:
![image](https://user-images.githubusercontent.com/25890405/206272243-2732f592-c13d-433b-a745-4d0f81d31002.png)

When building the add-on myself and installing from the ankiaddon file I get this error:
```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨ActivityWatch for Anki⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/home/julius/.var/app/net.ankiweb.Anki/data/Anki2/addons21/aw_watcher/__init__.py", line 17, in <module>
    from aw_client import ActivityWatchClient
ModuleNotFoundError: No module named 'aw_client'
```

My anki version info:
```
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.10 Qt 5.15.2 PyQt 5.15.5
```
I'm running archlinux and using the anki flatpak

**Comment by abdnh** [comment]
> When trying to install from ankiweb with the code `567877061` I get this error:

I can't reproduce this on the 2.1.54. This message should normally only appear when you click the _Check for Updates_ button. This could be an issue specific to the flatpak version.

> When building the add-on myself and installing from the ankiaddon file I get this error:

You first have to run `make vendor` to bundle the required library in the source folder.

You can anyway download a zip of the add-on directly from AnkiWeb using this link: https://ankiweb.net/shared/download/567877061?v=2.1&p=54

**Comment by MinmoTech** [comment]
Downloading the zip manually works, thank you so much for that!
